### ISSUE TITLE
Is this still being managed?

### ISSUE THREAD

**Issue by ruchern** [callumlocke/json-formatter#101]
At least for pull requests, are you able to just merge them?

**Comment by ssi-anik** [comment]
I don't think so.  :upside_down_face:

**Comment by ruchern** [comment]
@ssi-anik Sad, wanted to request if this can be ported to Safari.

**Comment by ssi-anik** [comment]
There's no license, so you can fork it. do whatever you wish to do. I am not sure about the consequences tho. :|

**Comment by ruchern** [comment]
I am not sure how to create Safari extensions. It is not like Chrome which has the`manifest.json` file

**Comment by ssi-anik** [comment]
read some blogs check it how to make it. I don't have mac. :rofl:
