### ISSUE TITLE
JSONFormatter automatically rounds numbers with size larger than 2^53

### ISSUE THREAD

**Issue by InKolev** [callumlocke/json-formatter#106]
JSONFormatter **automatically rounds** numbers with size larger than **2^53**, because of the way JavaScript numbers are implemented.

The problem exists for numbers of type **long**, **double**, **decimal**, **BigInteger** and so on.

Applying images to show the output when the **json** is **parsed** and when its **raw**. 

**PARSED**:
![image](https://cloud.githubusercontent.com/assets/6628205/25953860/4422d0b4-366d-11e7-8635-109b4f7b49e5.png)

**RAW**:
![image](https://cloud.githubusercontent.com/assets/6628205/25953830/35c27704-366d-11e7-991c-47c28461f67d.png)

**Comment by Joshfindit** [comment]
https://github.com/callumlocke/json-formatter#why-are-large-numbers-not-displayed-accurately

**Comment by InKolev** [comment]
@Joshfindit Ah, yes, he already noted this. 

So from what I've read in the description, it seems like the plugin is designed to work this way (mimicking what V8 is seeing) and in such case - there's nothing to be fixed.

I'm closing the issue.
