### ISSUE TITLE
local files

### ISSUE THREAD

**Issue by bgbruno** [callumlocke/json-formatter#135]
I open local file json and it not work

**Comment by LeeviHalme** [comment]
@bgbruno That's because chrome doesn't allow it's extensions to modify local files/pages. There is no current fix to that and it has nothing to do with this extension. You can close this issue now :)

**Comment by bgbruno** [comment]
OK thx

I use for that upload to https://webcloud.io :-)

**Comment by bgbruno** [comment]
chrome doesn't allow it's extensions to modify local files/pages
OK thx

I use for that upload to https://webcloud.io :-)




Bruno

--

BG Studio

TVORÍM ONLINE SVET
Obchod, Články, Stránky
https://bgstudio.online

Pre zrýchlenie konverzácie mi môžete napísať tu
https://bgstudio.online/chat

Viac o používaných značkách tu
https://bgstudio.online/itags

**Comment by tvkit** [comment]
The following option works on v84. See #118.  

`Chrome Options -> More Tools -> Extensions -> JSON Formatter -> Details -> Allow access to file URLs`
