### ISSUE TITLE
Extension isn't triggered

### ISSUE THREAD

**Issue by vonbarnekowa** [callumlocke/json-formatter#140]
Hey!

Having some issues with your extension. The first case is on my localhost. Here is a curl of my API endpoint:
```
> GET /version HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 21
< Content-Type: application/json
< Date: Sat, 29 Dec 2018 15:38:33 GMT
<
{'version': '1.0.0'}
* Connection #0 to host localhost left intact 
```

I searched in the issue history and found that if the `Content-Type: application/json` is missing. However, it isn't missing in my request..

The second problem is a more vague problem. The extension is never triggered on JSON responses. I know its a vague description but I can't make it work. I tried on your example links and on some other like [this](https://jsonplaceholder.typicode.com/todos/1).

The extension run on Chrome 71.0.3578.98 on MacOS 10.13.6.

**Comment by jpmetcalf** [comment]
If you are using Ghostery, that is probably your issue. It seems Ghostery somehow interferes with this plugin now.

**Comment by deogw** [comment]
Yes, because Ghostery. Just disable purple box.

![image](https://user-images.githubusercontent.com/16454188/62819124-f86fee00-bb7a-11e9-9fb3-204a54e217ba.png)

**Comment by UserNotFound** [comment]
Just an update, it's now called "Tracker-Tally".

![image](https://user-images.githubusercontent.com/1580788/103022526-5e0f1100-4509-11eb-850c-50449d696ddd.png)
