### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by ghost** [callumlocke/json-formatter#157]
I just downloaded the extension and have it turned on and allowed it all the permissions. When I open up a URL with JSON on it it just doesn't do anything. Would appreciate some help.

Here is the URL I currently am using to test it.

https://efa.mvv-muenchen.de/ng/XSLT_DM_REQUEST?outputFormat=JSON&language=en&stateless=1&coordOutputFormat=MRCV&useRealtime=1&zope_command=enquiry&type_dm=stop&name_dm=Zugspitzstra%C3%9Fe&itOptionsActive=1&ptOptionsActive=1&mergeDep=1&useAllStops=1&mode=direct&anyMaxSizeHitList=10000&useAllStops=1

**Comment by jamjar919** [comment]
![image](https://user-images.githubusercontent.com/5647724/87036544-e2333d80-c1e2-11ea-9383-e1d89879e0ac.png)

Your header type is text/html, you need to return application/json.

**Comment by UserNotFound** [comment]
If you use Ghostery, you need to turn off the "Tracker-Tally" notification option.

![image](https://user-images.githubusercontent.com/1580788/103022526-5e0f1100-4509-11eb-850c-50449d696ddd.png)
