### ISSUE TITLE
Not working in Chrome 84

### ISSUE THREAD

**Issue by asebold** [callumlocke/json-formatter#165]
Hi, love this extension. I upgraded to Chrome Version 84.0.4147.89 and it suddenly stopped working when the Content-Type returned from the server is application/json.

**Examples**

https://indie-hackers.firebaseio.com/loadingQuotes/78.json - This will not format for me.

Response headers:
````
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 204
Content-Type: application/json; charset=utf-8
Date: Sat, 01 Aug 2020 21:12:00 GMT
Server: nginx
Strict-Transport-Security: max-age=31556926; includeSubDomains; preload
````

https://graph.facebook.com/coca-cola?callback=whatever - But this one does format correctly.

Response headers:
````
access-control-allow-origin: *
alt-svc: h3-29=":443"; ma=3600,h3-27=":443"; ma=3600
cache-control: no-store
content-encoding: br
content-length: 153
content-type: text/javascript; charset=UTF-8
date: Sat, 01 Aug 2020 21:10:24 GMT
expires: Sat, 01 Jan 2000 00:00:00 GMT
facebook-api-version: v3.1
pragma: no-cache
status: 200
strict-transport-security: max-age=15552000; preload
vary: Accept-Encoding
````

**Comment by tiagomacarios** [comment]
@asebold I was having the same problem. After some debugging I see that my issue was that 2 other extensions where adding nodes to the html and messing with this extension. The link you posted works fine for me now (86.0.4240.75). Try inspecting the json and figuring out what other extension is causing the issue for you.

**Comment by onuar** [comment]
@tiagomacarios' solution works for me. Mine was [Ghostery](https://chrome.google.com/webstore/detail/ghostery-%E2%80%93-privacy-ad-blo/mlomiejdfkolichcflejclcbmpeaniij#). After disabling this, json-formatter is working again properly. I didn't debug so I don't know how Ghostery prevents json-formatter.

**Comment by creechy** [comment]
Ghostery seems to be the problem for me as well, on Microsoft Edge Chromium 87.0.664.57.

**Comment by creechy** [comment]
This appears to be a Ghostery issue, at least for me. See https://github.com/ghostery/ghostery-extension/issues/86. The work around for me is to disable the Ghostery "purple box" (Ghostery -> Settings -> Tracker Tally)

**Comment by asebold** [comment]
Confirmed, Ghostery is the problem for me as well. I removed the Tracker Tally (purple box) and this extension works fine now.
