### ISSUE TITLE
Doesn't work for php generated JSON

### ISSUE THREAD

**Issue by blueedgetechno** [callumlocke/json-formatter#172]
I was scrapping the API,

https://www.jiosaavn.com/api.php?__call=autocomplete.get&query=abcd

And it didn't work.

Any solution or alternative?

**Comment by calba5141114** [comment]
The reason it failed is that the API Response returned the wrong content type. 
I believe the extension only loads/parses ```application/json``` responses
<img width="577" alt="Screen Shot 2021-04-26 at 7 29 37 PM" src="https://user-images.githubusercontent.com/26678464/116175737-bfb4d700-a6c5-11eb-8d22-8dad9e5af975.png">

**Comment by callumlocke** [comment]
Thanks, that's right, it doesn't work with `text/html`. It doesn't care about the MIME type as long as it's something the browser usually renders as plain text, like `application/json` or `text/plain`.
