### ISSUE TITLE
Doesn't work in Chrome 89

### ISSUE THREAD

**Issue by vdegenne** [callumlocke/json-formatter#173]
Doesn't work in Chrome 99.
Please remove from store.
Waste of time for many users.
Thanks

**Comment by ceo** [comment]
do you come from the future ?

**Comment by vdegenne** [comment]
@ceo sorry I meant 89. But still, doesn't work. Wasted my time

**Comment by callumlocke** [comment]
Never reproduced this but it seems to work in Chrome 96.
