### ISSUE TITLE
CALLUMLOCKE.CO.UK = SPAM VIRUS WEBSITE

### ISSUE THREAD

**Issue by Sunhat** [callumlocke/json-formatter#184]
https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa?hl=en

THIS WEBSITE WITH YOUR EXTENSION ON SHOWS CALLUMLOCKE.CO.UK AS THE PUBLISHER.

THIS WEBSITE REDIRECTS TO A SPAM EXTENSION VIRUS

FIX IT OR GET TAKEN DOWN FOR HOSTING VIRUSES

**Comment by callumlocke** [comment]
Thanks for bringing that to my attention, I guess I forgot to renew that domain and someone has squatted it. But first, who are you and why the fuck are you talking to me like that?

**Comment by callumlocke** [comment]
I've now changed the owner domain to callumlocke.com, should come through whenever the Store approves the change
