### ISSUE TITLE
Chrome is complaining about access to `navigator`

### ISSUE THREAD

**Issue by eoghanmurray** [callumlocke/json-formatter#185]
https://github.com/callumlocke/json-formatter/blob/e494f29f613d6d682e67b4acbc571812bf1638b5/extension/js/content.js#L315

"A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
"

With a link to https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html

Could the code just be updated to accept either `metaKey` or `ctrlKey` as a valid modifier irrespective of platform?

**Comment by HoffmannP** [comment]
Any updates on this issue?

**Comment by eoghanmurray** [comment]
I believe my PR was merged, so warnings should go away in next update (I'm not involved in this project in terms of publishing the extension, just wrote this PR)
