### ISSUE TITLE
System dark mode issues conflicts with extension colors

### ISSUE THREAD

**Issue by tomasvts** [callumlocke/json-formatter#190]
When you set the "Dark appearance" on Mac
<img width="670" alt="image" src="https://user-images.githubusercontent.com/4351937/165964753-7fa895cd-23b5-4c43-af21-fa2a7145654d.png">

Chrome will autodetect this and display whenever it can the page in black mode
<img width="516" alt="image" src="https://user-images.githubusercontent.com/4351937/165964330-17ba79fc-f05e-43cb-b1d0-d332138dbcb6.png">

This can be checked testing this:
```window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches```

Returns true on dark mode devices.

**Comment by martinsuchan** [comment]
Same problem here in Edge 101 with default Dark mode.

**Comment by mlarmet** [comment]
Same for me on chrome

**Comment by vlaube** [comment]
up

**Comment by callumlocke** [comment]
Thanks, now fixed in v0.6.2
