### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by sites21** [callumlocke/json-formatter#196]
From this issue, plugin doesn't work
`chrome-extension://bcjindcccaagfpapjjmafapmmgkkhgoa/js/content.js:77:64`

**Comment by asch3ron** [comment]
Hello, we already submitted a request there #194 I hope this will get fix soon!

**Comment by sites21** [comment]
Thank you

**Comment by callumlocke** [comment]
Thanks, this has been fixed in v0.6.2, released yesterday
