### ISSUE TITLE
Update Edge extension

### ISSUE THREAD

**Issue by onbuyuka** [callumlocke/json-formatter#203]
Edge extension is still on version v0.6.0 and is missing the important fix #191

**Comment by m-a-x-s-e-e-l-i-g** [comment]
Really annoying. Luckily you can download the extension on the Chrome Webstore to work around this issue.
https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa/

**Comment by callumlocke** [comment]
I have nothing to do with the Edge extension, sorry
