### ISSUE TITLE
The edge version is behind the chrome version

### ISSUE THREAD

**Issue by desbest** [callumlocke/json-formatter#216]
The edge version is behind the chrome version
Can you make sure the Edge Addons Gallery receives the latest version?

**Comment by desbest** [comment]
Someone has forked and taken over to newly maintain a previously abandoned and defunct project.

[Github repository of Nicole's fork](https://github.com/nicole-ashley/json-formatter)
[Google chrome store listing](https://chrome.google.com/webstore/detail/json-formatter/mhimpmpmffogbmmkmajibklelopddmjf)

**Comment by callumlocke** [comment]
The Edge version is nothing to do with me.
