### ISSUE TITLE
Someone's forked to newly maintain this abandoned extension

### ISSUE THREAD

**Issue by desbest** [callumlocke/json-formatter#217]
Someone has forked and taken over to newly maintain a previously abandoned and defunct project.

[Github repository of Nicole's fork](https://github.com/nicole-ashley/json-formatter)
[Google chrome store listing](https://chrome.google.com/webstore/detail/json-formatter/mhimpmpmffogbmmkmajibklelopddmjf)

**Comment by callumlocke** [comment]
It's not abandoned (it's more recently updated than that fork, actually!).

I'm working on an update that aims to make JSON Formatter survive the manifest v3 apocalypse that Google has scheduled for January 2023.
