### ISSUE TITLE
Collapse icon not appearing for JSON with top-level object

### ISSUE THREAD

**Issue by jd-brennan** [callumlocke/json-formatter#221]
The icon for collapsing doesn't appear for JSON files that are an object, {}.
Only seems to work for JSON files are are an array, [].

For instance: https://raw.githubusercontent.com/callumlocke/json-formatter/master/tsconfig.json
![image](https://user-images.githubusercontent.com/117212701/205129910-ead7022d-e491-48ef-8256-5b916840b852.png)

Collapsing still works. You can click to the left of "compilerOptions" to collapse.

**Comment by callumlocke** [comment]
I can't replicate. Are you using the extension installed from the store or the latest code from GitHub? And what browser/OS?

**Comment by jd-brennan** [comment]
Noticed that it only seems to happen with githubusercontent which serves up the file with Content-Type: text/plain

If I copy the same file to my laptop and serve it from there with Content-Type: application/json then the icons appear.

**Comment by jd-brennan** [comment]
Also installing the Chrome extension HTTP Headers makes JSONFormatter show the icons. Very strange!

**Comment by callumlocke** [comment]
Hmm that is strange. Well now v0.7.0 is now out (it just got released on the store about 30 minutes ago) and everything has been refactored a lot, so can you see if the problem still exists now? Hopefully you should get auto-updated, or you might need to restart Chrome.

**Comment by jd-brennan** [comment]
Yes! Working in 0.7.0. Thanks.  And I did get auto-updated. Didn't even have to restart Chrome.
