### ISSUE TITLE
div#formattedJson id and classes changed

### ISSUE THREAD

**Issue by jsonengler** [callumlocke/json-formatter#222]
i noticed that a lot of my tampermonkey scripts broke today. i'm looking into it, and i realize you changed some of the id/class names which my script is specifically using. by any chance do you have a list of these changes i can look at?

for example, this is the json in question:
>{"error":"not_found","reason":"missing"}

i'm using this jquery selector:
>$("div#formattedJson > span.kvov.arrElem.rootKvov > span.blockInner")

after the update to 0.7.0, this doesn't find what i'm looking for, so i have to replace it with this:
>$("div#jsonFormatterParsed > span.entry.arrElem > span.blockInner")

**Comment by Cvr223** [comment]
> i noticed that a lot of my tampermonkey scripts broke today. i'm looking into it, and i realize you changed some of the id/class names which my script is specifically using. by any chance do you have a list of these changes i can look at?
> 
> for example, this is the json in question:
> >{"error":"not_found","reason":"missing"}
> 
> i'm using this jquery selector:
> >$("div#formattedJson > span.kvov.arrElem.rootKvov > span.blockInner")
> 
> after the update to 0.7.0, this doesn't find what i'm looking for, so i have to replace it with this:
> >$("div#jsonFormatterParsed > span.entry.arrElem > span.blockInner")

琐堙Ҕ椓Ẉ七쓘稻㏑ࡰ埞슞᰾�닪塳뫷Θꃕ◴떛觞鷷ꀴ�ᣖ쓲옓埱塠麣䃐來蹌䑊슋⥄䤯팇㣂噏쎊棔ᡊ滰绋⃈댟쎋䕚큺�

**Comment by callumlocke** [comment]
Sorry about this. And it's probably going to happen again soon as I'm refactoring it.

If you just want your old tampermonkey stuff to keep working without any changes, one option is you could just check out the previous version (think it's [v0.6.2](https://github.com/callumlocke/json-formatter/tree/v0.6.2) and install that from source. Obviously you then won't get future updates though.

As for your specific problem, I am not completely sure but you should be able to figure out what selector you need from the devtools. It's probably just one of the class names changed.
