### ISSUE TITLE
Feature Request: Add toggle to switch between light vs dark mode

### ISSUE THREAD

**Issue by alexdonh** [callumlocke/json-formatter#224]
I'm definitely not the only person. I'm using dark mode still I like to see web pages including this json friendly formatted page in white..

Is it possible to have a dropdown select in Extension options page? like this:

- System default
- Light
- Dark

**Comment by jack3147-huang** [comment]
Me too,
wish there were multiple options.

**Comment by nanonz** [comment]
Me too, I wish it would happen.

**Comment by callumlocke** [comment]
Coming soon

**Comment by callumlocke** [comment]
This is now done in v0.7.1, currently awaiting approval in the Chrome Web Store (usually takes 1-2 days). Or you can install from source to try it now.

Here is the new Options UI:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/250617/210139076-73797e28-0cbf-46cd-b0a6-ba14652342eb.png">

Please let me know if it works!

**Comment by alexdonh** [comment]
Work perfectly fine on my end! Many thanks!
