### ISSUE TITLE
Support data uri's in browser location bar?

### ISSUE THREAD

**Issue by benknight** [callumlocke/json-formatter#24]
I'd love to be able to type `data:application/json, <json>` into the location bar and get pretty formatted JSON from this plugin.

**Comment by pascience** [comment]
+1 for this

**Comment by callumlocke** [comment]
If this doesn't work, then I think Chrome must be blocking it as some kind of security measure.

If I'm wrong and there's a way I can enable extension access to data URI pages, please open again
