### ISSUE TITLE
JSON Formatter fail to format 64 bit integers

### ISSUE THREAD

**Issue by XXiemeciel** [callumlocke/json-formatter#248]
Hi,

There is a bug in the formatter that is you have 64 bit integers the raw and formatted values are different

![2023-05-18_14-45-40](https://github.com/callumlocke/json-formatter/assets/68449283/488c8cda-a759-4f44-9eda-67876909cde7)

**Comment by LouissXI** [comment]
Hi,

Just found it by myself too. I'll try to dig into the source code to try to find a fix to it.

**Comment by callumlocke** [comment]
See https://github.com/callumlocke/json-formatter#why-are-large-numbers-not-displayed-accurately

**Comment by XXiemeciel** [comment]
Is node-bigint not working for this use case ?
