### ISSUE TITLE
Please test this extension in Chrome canary

### ISSUE THREAD

**Issue by naman-narula** [callumlocke/json-formatter#266]
A new pretty print feature has been introduced in Chrome. The extension is functional but the pretty print bar appears on top of the UI created by this extension.

**Comment by rishiraj88** [comment]
nice

**Comment by reilg** [comment]
![image](https://github.com/callumlocke/json-formatter/assets/492972/8d683562-ce8f-459c-9c8b-e408df91d77b)

I would like to keep using the extension because the feature in Chrome doesn't have highlighting, afaict. 

I cannot find a way to disable the feature in Chrome itself. Anyone got suggestions?

**Comment by c4ldas** [comment]
> I would like to keep using the extension because the feature in Chrome doesn't have highlighting, afaict.
> 
> I cannot find a way to disable the feature in Chrome itself. Anyone got suggestions?


I don't have Chrome here, but there is a way on Edge and Brave. Maybe Chrome also has any of the options.

On Edge, you can disable it on the flags webpage:

`edge://flags/#edge-json-viewer`

![image](https://github.com/callumlocke/json-formatter/assets/75918726/7f8ff3d5-659c-4ddf-9500-c4a7799deeb3)


On Brave, you can add the following flag to the shortcut:

`--disable-blink-features=PrettyPrintJSONDocument`

https://community.brave.com/t/how-to-disable-new-pretty-print/506408/9

**Comment by JonathanBout** [comment]
This is now in my non-canary Chrome but I can't find the option in chrome://flags. I don't have any extension dev experience but it shouldn't be too hard to hide the element right?

**Comment by guohuihot** [comment]
The latest version of edge 123.0.2420.8 no longer has this setting. What should I do
