### ISSUE TITLE
Seems broken since today - doesnt format anymore

### ISSUE THREAD

**Issue by vincentwinkel** [callumlocke/json-formatter#270]
Hello,
First of all, I love this extension. It was working perfectly until yesterday and now this is what I get (when parsed) with v0.7.2

<img width="1781" alt="Screenshot 2024-03-28 at 10 24 43" src="https://github.com/callumlocke/json-formatter/assets/1402505/7d4d30cb-b7bc-4303-84e3-fdcf14c226fb">

instead of this with v0.2.3

<img width="752" alt="Screenshot 2024-03-28 at 10 24 59" src="https://github.com/callumlocke/json-formatter/assets/1402505/ec64ec91-6cfa-4703-8c10-33a2c268b077">

**Comment by JustinGT** [comment]
An example of a non-formatted url: https://qrng.anu.edu.au/API/jsonI.php?length=1&type=uint8

I'm not sure when the problem started, but I can say for sure that I noticed it when I updated Chrome to "Version 123.0.6312.86 (Official Build) (64-bit)" today.

**Comment by josecabral-afs** [comment]
I'm also seeing this
If I disable the JSON Formatter extension I now see this:

![image](https://github.com/callumlocke/json-formatter/assets/97891541/2353bbaf-e18b-4209-8802-5c64426b1ef2)

So probably this is the reason for it to be broken?

**Comment by Grouloo** [comment]
The problem seems tied to a wrong parsing of an object when applying styles, or something like that.
If you paste the content of style.css or styleDark.css in the <style> tag, it works as expected.

![Capture d’écran 2024-03-28 à 11 29 34](https://github.com/callumlocke/json-formatter/assets/16732031/c9d1df30-9d8c-42c9-867c-3431f495bc34)

**Comment by vincentwinkel** [comment]
For some reasons, it works now

**Comment by vincentwinkel** [comment]
Ah sorry, I closed the ticket too fast without refreshing the thread and didnt see your messages guys :grimacing:

**Comment by JustinGT** [comment]
Looks like the change has started to propagate - mine is now working again.
