### ISSUE TITLE
Incompatible with some other Extensions

### ISSUE THREAD

**Issue by colllin** [callumlocke/json-formatter#5]
I found a bug on this line:
https://github.com/callum85/json-formatter/blob/master/extension/js/content.js#L218
where this extension will fail to activate if the user has other extensions installed that modify the DOM before this extension is run.  I'm not sure if the fix involves bumping up the priority of this extension somehow?  Or bumping up the order in which the script is run?  An example extension that creates the error is: https://chrome.google.com/webstore/detail/hinehgnhgiohbfpbpgkjnelkcgdkcgha?hl=en-US&utm_source=chrome-ntp-launcher

**Comment by keanolane** [comment]
same issue when this extension is active: https://chrome.google.com/webstore/detail/ghostery/mlomiejdfkolichcflejclcbmpeaniij?hl=en

**Comment by callumlocke** [comment]
Closing this now as it's been refactored, including changing the logic for checking if the page is a JSON page, which I'm hoping means it will make it much less likely to clash with other extensions. (But if there are still problems, please open a new issue, if possible telling me exactly which extensions clash.)

Old logic: check if the `body` contains a *single* child that is a `pre` containing something that parses as a JSON object/array. (This was too fragile, as other extensions often insert a hidden `div` or something in the `body` before JF's check.)

New logic: same except it now it only looks for a `body > pre`; it doesn't care if there happen to be other elements.
  - NB. there is a trade-off - there is now increased risk of false positives (detecting a page as JSON when it's really just a regular web page) but I'm hoping this will be very rare.
