### ISSUE TITLE
doesn't format when top level is an unnamed array

### ISSUE THREAD

**Issue by keithmdragon** [callumlocke/json-formatter#61]
doesn't format when top level is an unnamed array
[
  {
    "cnt":1,
    "name":"American",
    "pk":7
  },
  {
    "cnt":2,
    "name":"Celebrities",
    "pk":3
  },
  {
    "cnt":1,
    "name":"Region",
    "pk":9
  }
]

**Comment by refringe** [comment]
:+1:

**Comment by SoulCover** [comment]
+1

**Comment by ameykpatil** [comment]
+1

**Comment by callumlocke** [comment]
Weird, top-level arrays work correctly for me:

![image](https://cloud.githubusercontent.com/assets/250617/12421159/badf25be-beb8-11e5-9df8-6ae283c6af83.png)

Can anyone give me a live URL showing the bug?

**Comment by boynet** [comment]
also working for me

**Comment by keithmdragon** [comment]
this might be fixed, or at least works for me in one case, with a similar unnamed array being returned. 

i'm using chrome: Version 47.0.2526.111 m

Keith

**Comment by SoulCover** [comment]
Probably doesn't work when `Content-Type`-Header is set to `text/html`.

**Comment by callumlocke** [comment]
will reopen this if someone can give me a URL that shows the problem.
