### ISSUE TITLE
Wrong item count

### ISSUE THREAD

**Issue by morrismukiri** [callumlocke/json-formatter#74]
Wrong count for array items. You get //9 items if the json array has 10 objects
![jsonformat bug](https://cloud.githubusercontent.com/assets/804653/15288949/4ddb6dbc-1b77-11e6-8e11-2193afae2f29.PNG)

**Comment by callumlocke** [comment]
The "9 items" in your screenshot refers to how many keys there are inside each collapsed object, not the length of the parent array

If you collapse the array itself, then you should see the array length

Let me know if it's still a problem
