### ISSUE TITLE
Not working for some unknown reason

### ISSUE THREAD

**Issue by mkwsra** [callumlocke/json-formatter#81]
Thanks a lot for such great tool, I tried others but they aren't as good as yours.

Please note that in the last peroind ~month it's not working at all and for unknown reason (to me).

Chrome: Version 53.0.2785.116 (64-bit)
OS: Mac OS Sierra 10.12.1 Beta (16B2327e)

**Comment by vot** [comment]
+1

It seems to be working in incognito mode for me but not in normal browsing mode.

Chrome: Version 53.0.2785.116 (64-bit)
OS: Mac OS X Yosemite 10.10.5

**Comment by webdevian** [comment]
+ 1

Version 53.0.2785.143 (64-bit)
OSX 10.11.6 (15G31)

A couple other json viewing extension are also broken for me so I guess something in chrome core changed and broke the json detection

**Comment by discotroll65** [comment]
It wasn't working for me either, and then I realized that it was because the request was coming in with a content Type of text/html

I made a pull request, should fix it: https://github.com/callumlocke/json-formatter/pull/89

**Comment by webdevian** [comment]
It seems to be working again for me for the last few weeks
Version 54.0.2840.71 (64-bit)

**Comment by nikrolls** [comment]
This issue is fixed in my fork: https://github.com/nikrolls/json-formatter
