### ISSUE TITLE
[NFR] JSON didnt support int64, lets use sidorares/json-bigint

### ISSUE THREAD

**Issue by ovr** [callumlocke/json-formatter#96]
Hey!

About this Problem

> Why are large numbers not displayed accurately?

This is a limitation of JavaScript (and therefore JSON). The largest possible number is Number.MAX_SAFE_INTEGER, or 9007199254740991. If you try to use a number larger than this in JavaScript/JSON, you'll lose accuracy.

The idea of JSON Formatter is to show you how the computer sees your JSON, so we don't attempt to circumvent this limitation, otherwise that would give a misleading representation of your data. It's better to see exactly what V8 sees.

https://github.com/sidorares/json-bigint

And write `(``)` value what JS see if it's > MAX_SAFE_INTEGER

Thanks

**Comment by nikrolls** [comment]
This is fixed in https://github.com/nikrolls/json-formatter/releases/tag/0.10.0, currently rolling out to the Chrome and Edge stores.
