### ISSUE TITLE
Readme's "Some URLs to try it on" are dead

### ISSUE THREAD

**Issue by mlsteele** [callumlocke/json-formatter#98]
Just a heads up, the "Some URLs to try it on" are all dead links.

**Comment by ssi-anik** [comment]
Nah bro, twitter is up with error, still giving json. :smiley:

**Comment by achtur** [comment]
> Just a heads up, the "Some URLs to try it on" are all dead links.

Hey! Same here. None of these three are working for me.

> Some URLs to try it on:
> 
> http://feeds.delicious.com/v2/json/popular?callback=hello
> http://gdata.youtube.com/feeds/api/standardfeeds/most_popular?alt=json&v=2
> http://twitter.com/statuses/public_timeline.json

**Comment by ssi-anik** [comment]
> > Just a heads up, the "Some URLs to try it on" are all dead links.
> 
> Hey! Same here. None of these three are working for me.
> 
> > Some URLs to try it on:
> > http://feeds.delicious.com/v2/json/popular?callback=hello
> > http://gdata.youtube.com/feeds/api/standardfeeds/most_popular?alt=json&v=2
> > http://twitter.com/statuses/public_timeline.json

Are you guys still using this formatter? I have switched to https://github.com/rbrahul/Awesome-JSON-Viewer

**Comment by achtur** [comment]
> > > Just a heads up, the "Some URLs to try it on" are all dead links.
> > 
> > 
> > Hey! Same here. None of these three are working for me.
> > > Some URLs to try it on:
> > > http://feeds.delicious.com/v2/json/popular?callback=hello
> > > http://gdata.youtube.com/feeds/api/standardfeeds/most_popular?alt=json&v=2
> > > http://twitter.com/statuses/public_timeline.json
> 
> Are you guys still using this formatter? I have switched to https://github.com/rbrahul/Awesome-JSON-Viewer

Oh damn, this looks amazing! Just installed it :) Thank you so much @ssi-anik!

**Comment by callumlocke** [comment]
Updated now, thanks
